services:
    tacitus89.piwikstats.listener:
        class: tacitus89\piwikstats\event\listener
        arguments:
            - @config
            - @config_text
            - @controller.helper
            - @template
            - @user
        tags:
            - { name: event.listener }

    tacitus89.piwikstats.main.controller:
        class: tacitus89\piwikstats\controller\main_controller
        arguments:
            - @config
            - @config_text
            - @controller.helper
            - @template
            - @user
            - @cache.driver
